<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>disable</Nullable>

    <AssemblyName>DashAttackMacro</AssemblyName>
    <RootNamespace>DashAttackMacro</RootNamespace>

    <AssemblyCompany>sophistcraft</AssemblyCompany>
    <AssemblyCopyright>Copyright © 2026 sophistcraft</AssemblyCopyright>

    <!-- 빌드결과물 dll만 깔끔하게 뽑기 위한 옵션 -->
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>

    <!-- InputEvent.data->eventId 접근 -->
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>..\lib\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>..\lib\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\lib\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\lib\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>..\lib\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>..\lib\Unity.InputSystem.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <!-- 빌드 성공 시 해당 폴더로 자동 복사 -->
  <Target Name="CopyToPlugins" AfterTargets="Build">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="C:\SteamLibrary\steamapps\common\Sephiria\BepInEx\plugins" />
  </Target>

</Project>
